# Generated by Django 3.0.4 on 2020-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, unique=True)),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('confirmed', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('recovered', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ('confirmed',),
            },
        ),
    ]
